---
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---
  
  <link rel="stylesheet" href="styles.css" type="text/css">

  ```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

My full CV is available [here](files/jragusa_cv.pdf)

## Professional Experiences
Lecturer at the [University of Geneva](https://www.unige.ch/sciences/terre/en/]) (**2019**). Regional Geology for 2nd year Bachelor (course: 12T005-CR and fields: 12T506-TT, 12T510-TT).

Scientific consultant at the [Chablais Geopark](http://www.geopark-chablais.com/) (**2017--present**).
  
## Education

PostDoc (**2015--2016**). University of Geneva, Switzerland. Supervisor : Pascal
Kindler.

PhD Student in sedimentary geology (**2009--2015**). University of Geneva, Switzerland. Supervisor : Pascal Kindler.

Master Student in sedimentary geology (**2006--2009**). University of Geneva, Switzerland. Supervisor : Pascal Kindler.

Master 1 in paleoprimatology, paleontology and paleoenvironnements (**2004--2005**). University of Poitiers, France.

Bachelor in geology (**2001--2004**). University of Dijon, France.

## Professional Memberships

Swiss Geological Society

Association des sédimentologues français

## Awards & Grants

Bourse Lombard (**2009**). Master thesis Award (1000 CHF), Société de Physique et d’Histoire naturel de Genève.

## Organisation

Kindler P, Ragusa J, Slootman A (**2014**). Pre-Meeting IAS-Student Field Trip: The Mt. Salève, 19th International Sedimentology Congress (ISC), Geneva.

Kindler P (**2014**). From passive margin to foreland basin: stratigraphy and sedimentology of the Bornes-Aravis massif (Haute-Savoie, France) from the Triassic to the Oligocene, 19th International Sedimentology Congress (ISC), Geneva.

## Short courses

4th Sedimentary Provenance Analysis (**2014**). University of Göttigen, Germany.

1st School of Heavy Mineral Analysis (**2013**). University of Milano-Bicocca, Italy.

## Field courses

Remnants of the ancient Tethys margins preserved in the Tasna, Platta, Err, Bernina and Ortler nappes in the Alps (**2017**). Switzerland-Italy, Swiss Geological Society, leader: Gianreto Manatschal (University of Strasbourg).

Carambar 2 (**2016**). Deep-sea core drilling project off Bahamas, Ifremer, leader: Thierry Mulder (University of Bordeaux).

Workshop on Alpine Carbonate Platforms (**2015**). France, Doctoral school of Western Switzerland (CUSO), leader: Pascal Kindler (University of Geneva).

Facies and structure of the Permian to Jurassic oceanic assemblage with a Panthalassic affinity of the Mino terrane (**2013**). Terrane central Japan, Japan, Doctoral school of Western Switzerland (CUSO), leader: Rossana Martini (University of Geneva).

Tectonics and sedimentation along an active plate boundary (**2012**) New Zealand, Doctoral school of Western Switzerland (CUSO), leader: Guy Simpson (University of Geneva).

Modern and fossil carbonate environments (**2011**) Bahamas, Doctoral school of Western Switzerland (CUSO), leader: Pascal Kindler (University of Geneva).

## Analytical methods

<i class="fa fa-flask" style="font-size: 1.5em;"></i> **Sedimentary petrography** sieving, staining feldspars, heavy mineral separation (SPT), counting

<i class="fa fa-calculator" style="font-size: 1.5em;"></i> **Statistical analysis** cluster analysis, principal component analysis, Pearson coefficient, Aitchison’s log-ratio transformation

## Skills

<i class="fa fa-linux" style="font-size: 1.5em;"></i> Linux (Fedora) 

<i class="fa fa-windows" style="font-size: 1.5em;"></i> Windows

<i class="fa fa-desktop" style="font-size: 1.5em;"></i> Inkscape, QGIS, Libre office and Office

<i class="fa fa-terminal" style="font-size: 1.5em;"></i> LaTeX, R and RStudio, Git, Html/CSS (basic)

<i class="fa fa-language" style="font-size: 1.5em;"></i> English (good), French (native), Russian (basics)

## Interests

<i class="fa fa-camera" style="font-size: 1.5em;"></i> photo, hiking, running

<i class="fa fa-globe" style="font-size: 1.5em;"></i> OpenStreetMap and Wikipedia