---
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---
  
  <link rel="stylesheet" href="styles.css" type="text/css">

<a href="https://orcid.org/0000-0002-6597-7475"><font color="a6ce39">Orcid ID</font></a> and [Google Scholar](https://scholar.google.fr/citations?user=dcONfmgAAAAJ)

## Peer-reviewed Publications
**Ragusa J**, Ospina-Ostios LM, Kindler P, Sartori M (**2021**). Stratigraphic revision and reconstruction of the deep-sea fan of the Voirons Flysch (Voirons Nappe, Chablais Prealps). *Swiss Journal of Geosciences*, 114, doi: 10.1186/s00015-020-00383-1.

Mulder T, Gillet H, Hanquiez V, Reijmer JJG, Droxler AW, Recouvreur A, Fabregas N, Cavailhes T, Fauquembergue K, Blank DG, Guiastrennec L, Seibert C, Bashah S, Bujan S, Ducassou E, Principaud M, Conesa G, Le Goff J, **Ragusa J**, Busson J and Borgomanoa J (**2018**). Into the deep: A coarse-grained carbonate turbidite valley and canyon in ultra-deep carbonate setting. *Marine Geology*, 407:316-333, doi: [10.1016/j.margeo.2018.11.003](https://www.sciencedirect.com/science/article/abs/pii/S0025322718302032) [[PDF](files/Mulder2018.pdf)].

**Ragusa J**, Kindler P (**2018**). Compositional variations in deep-sea gravity-flow deposits. A case study from the Voirons Flysch (Voirons-Wägital complex, Chablais Prealps, France). *Sedimentary Geology*, 377:111-130, doi: [10.1016/j.sedgeo.2018.08.010](https://www.sciencedirect.com/science/article/pii/S0037073818302033) [[PDF](files/Ragusa2018b.pdf)].

**Ragusa J**, Ospina-Ostios LM, Spezzaferri S, Kindler P (**2018**). Revision of the planktonic foraminiferal biostratigraphy of the Voirons Flysch (Chablais Prealps, Haute-Savoie, France). *Swiss Journal of Geosciences*, 111:433–445, doi: [10.1007/s00015-018-0314-7](https://link.springer.com/article/10.1007%2Fs00015-018-0314-7) [[PDF](files/Ragusa2018a.pdf)].

Mulder T, Gillet H, Hanquiez V, Ducassou E, Fauquembergue K, Principaud M, Conesa G, Le Goff J, **Ragusa J**, Bashah S, Bujan S, Reijmer JJG, Cavailhes T, Droxler AW, Blank DG, Guiastrennec L, Fabregas N, Recouvreur A, and Seibert C (**2017**). Carbonate slope morphology revealing a giant submarine canyon (Little Bahama Bank, Bahamas). *Geology*, 46(1):31–34, doi: [10.1130/G39527.1](https://pubs.geoscienceworld.org/gsa/geology/article-abstract/46/1/31/522865/carbonate-slope-morphology-revealing-a-giant?redirectedFrom=fulltext) [[PDF](files/Mulder2017.pdf)].

**Ragusa J**, Kindler P, Segvic B, Ospina-Ostios LM (**2017**). Provenance analysis of the Voirons Flysch (Gurnigel nappe, Haute-Savoie, France): Stratigraphic and paleogeographic implications. *International Journal of Earth Sciences*, 106(8):2619–2651, doi: [10.1007/s00531-017-1474-9](http://link.springer.com/article/10.1007%2Fs00531-017-1474-9) [[PDF](files/Ragusa2017a.pdf)].

Ospina-Ostios LM, **Ragusa J**, Wernli R, Kindler P (**2013**). Planktonic foraminifera biostratigraphy as a tool in constraining the timing of flysch deposition: Gurnigel flysch, Voirons massif (Haute-Savoie, France). *Sedimentology*, 60:225–238, doi: [10.1111/sed.12013](http://onlinelibrary.wiley.com/doi/10.1111/sed.12013/abstract;jsessionid=5A54433B3561A853F6DBF83958E6C356.f03t03) [[PDF](files/Ospina-Ostios2013.pdf)].

## Submitted Publications

nothing yet :)

## Science outreach

**Ragusa J**, Decrouez, D, Frebourg, G (**2021**). Géologie du Vouan, un ancien cañon sous-marin à
l’emplacement incertain, *Nature et Patrimoine en Pays de Savoie*, in press.

## Dissertations

**Ragusa J** (**2015**). Petrograpy, stratigraphy and provenance analysis of the Voirons Flysch (Gurnigel nappe) in the Chablais Prealps (France). PhD Thesis, *University of Geneva*, official repository: [Archive ouverte UniGE](https://archive-ouverte.unige.ch/unige:75519)

**Ragusa J** (**2009**). Study of heavy mineral population in the Voirons Flysch and the Samoëns Sandstones. Master Thesis, *University of Geneva*

## Conference abstracts

Mulder T, Gillet H, Hanquiez V, Ducassou E, Fauquembergue K, Recouvreur A, Fabregas N, Principaud M, Reijmer J, Conesa G, Droxler A, Cavailhes T, Le Goff J, **Ragusa J**, Bashah S, Bujan S, Blank D, Guiastrennec L, Borgomano J, Seibert C (**2018**) Giant Canyons and Chute Pools in Deep-Sea Carbonate Environment (Bahamas). *Abstract for the ACE 2018 Annual Convention & Exhibition*, Salt Lake City UH, USA [[link](http://www.searchanddiscovery.com/abstracts/html/2018/ace2018/abstracts/2857683.html)].

**Ragusa J**, Kindler P (**2017**) Recognition of tectonic settings in collisional systems using bulk-rock geochemistry: an example from the accretionary wedge of the Western Alps. *Abstract for the 33rd International Meeting of Sedimentology*, Toulouse, France.

Fabregas N, Mulder T, Hanquiez V, Gillet H, Ducassou E, Fauquembergue K, Principaud M, Conesa G, Conesa G, Le Goff J, **Ragusa J**, Bashah S, Bujan S, Reijmer JJG, Cavailhes T, Droxler A, Recouvreur A, Guiastrennec-Faugas L, Blank D, Seibert C (**2017**). Carbonate slope morphology revealing deep-sea sediment transfer in Little Bahama Bank, Bahamas. *Abstract for the 33rd International Meeting of Sedimentology*, Toulouse, France.

Recouvreur A, Mulder T, Hanquiez V, Borgomano J, Reijmer JJG, Droxler A, Gillet H, Cavailhes T, Fabregas N, Guiastrennec-Faugas L, Fauquembergue K, Blank D, Bashah S, Bujan S, Seibert C, Ducassou E, Principaud M, Conesa G, Le Goff J, **Ragusa J** (**2017**). Large carbonate-fed deep-sea turbidite fan develloped at the mouth of a giant canyon along the Bahamian slope. *Abstract for the 33rd International Meeting of Sedimentology*, Toulouse, France.

Mulder T, Gillet H, Hanquiez V, Ducassou E, Fauquembergue K, Conesa G, Principaud M, Le Goff J, **Ragusa J**, Bujan S, Bashah S (**2017**). Carbonate slope morphology revealing bank-to-slope sediment transfer in Little Bahama Bank, Bahamas. *Abstract for the 19th European Geosciences Union (EGU) Meeting*, Vienna, Austria [[link](http://adsabs.harvard.edu/abs/2017EGUGA..1919235M)].

**Ragusa J**, Kindler P (**2016**). Influence of grain-size and framework composition in deep-sea gravity-flow deposits. Example from the Voirons Flysch (Gurnigel Nappe, Chablais Prealps, France). *Abstract for the 3rd Workshop of the Working Group of Sediment Generation (WGSG)*, Leuven, Belgium.

**Ragusa J**, Kindler P (**2016**). Relation between grain-size and modal composition in deep-sea gravity-flow deposits. Example from the Voirons Flysch (Gurnigel nappe, Chablais Prealps, France). *Abstract for the European Geosciences Union (EGU) Meeting*, Vienna, Austria [[link](http://adsabs.harvard.edu/abs/2016EGUGA..1813066R)].

**Ragusa J**, Kindler P (**2016**). Relation between grain-size and modal composition in deep-sea gravity-flow deposits. Example from the Voirons Flysch (Gurnigel nappe, Chablais Prealps, France). *Abstract for the SwissSed*, Fribourg, Switzerland.

**Ragusa J**, Kindler P (**2015**). Reconstructing the sediment provenance of the Voirons Flysch (Gurnigel Nappe, Haute-Savoie, France). *Abstract for the 12th Alpine Workshop*, Briançon, France.

Ospina-Ostios LM, **Ragusa J** (**2015**). The use biostratigraphic tools in dating the Voirons Flysch (Gurnigel Nappe, Haute-Savoie, France). *Abstract for the 12th Alpine Workshop*, Briançon, France.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2014**). Discovery of two major sediment sources for the Voirons Flysch (Gurnigel Nappe, Haute-Savoie, France). *Abstract for the 19th International Sedimentology Congress (ISC)*, Geneva, Switzerland.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2013**). Provenance analysis of the Voirons Flysch (Gurnigel nappe, Haute-Savoie, France): highlighting two major sources. *Abstract for the Swiss Geoscience Meeting (SGM)*, Lausanne, Switzerland.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2013**). Highlighting multiple sources for the Voirons Flysch (Gurnigel nappe, Chablais Prealps, Haute-Savoie,France) and stratigraphic implications. *Abstract for the 1st School of Heavy Mineral Analysis*, Milano, Italy.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2012**). Using Dickinson’s method for a better understanding of the origin of the Voirons Flysch (Gurnigel nappe, Haute-Savoie, France). *Abstract for the Swiss Geoscience Meeting (SGM)*, Berne, Switzerland.

Ospina-Ostios LM, **Ragusa J**, Kindler P (**2011**). New sedimentological and biostratigraphic data from the Voirons Flysch (Voirons Massif, Gurnigel nappe, Haute-Savoie, France) : Implications for Alpine geology. *Abstract for the Swiss Geoscience Meeting (SGM)*, Bernouilli-Matter symposium, Zurich, Switzerland.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2011**). Fault-controlled formation of a primary turbiditic channel within the Gurnigel Flysch in the Voirons Massif (Haute-Savoie, France) during the Late Eocene. *Abstract for the Swiss Geoscience Meeting (SGM)*, Zurich, Switzerland.

Ospina-Ostios LM, **Ragusa J**, Kindler P (**2010**), New biostratigraphic data from the Voirons Sandstones (Voirons massif, Haute-Savoie, France): implications for the paleogeography for the Gurnigel nappe. *Abstract for the Swiss Geoscience Meeting (SGM)*, Fribourg, Switzerland.

**Ragusa J**, Ospina-Ostios LM, Kindler P (**2010**), Preliminary results of the sedimentary petrography study of the Gurnigel flysch in the Voirons and Vouan massif. *Abstract for the Swiss Geoscience Meeting*, Fribourg, Switzerland.

Ospina-Ostios LM, **Ragusa J**, Kindler P (**2009**), New interpretation about turbidites in the Voirons Massif, Gurnigel Nappe (Haute-Savoie, France). *Abstract for the 27th International Association of Sedimentologists (IAS) Meeting*, Alghero, Italy.